export const labs = [
  {
    id: 'web-auth',
    name: 'User Authentication',
    path: '/labs/web-auth',
    pingoneType: 'Web App (OIDC)',
    grant: 'Authorization Code',
    clientType: 'Confidential',
    description: 'Classic server-side web SSO. The app stores tokens in an HTTP-only server session after the authorization code is exchanged server-side.',
    examTopics: ['Authorization Code flow', 'Confidential client', 'Server-side session management', 'ID token vs access token'],
  },
  {
    id: 'mobile',
    name: 'Mobile Support',
    path: '/labs/mobile',
    pingoneType: 'Native App',
    grant: 'Authorization Code + PKCE',
    clientType: 'Public',
    description: 'Simulates a native/mobile client using PKCE without a client secret. Uses a loopback redirect URI pattern common for mobile dev.',
    examTopics: ['PKCE', 'Public client', 'Native app redirect URIs', 'No client secret'],
  },
  {
    id: 'spa',
    name: 'Single Page Application',
    path: '/labs/spa',
    pingoneType: 'Single Page App',
    grant: 'Authorization Code + PKCE',
    clientType: 'Public',
    description: 'Browser-only SPA that performs the OAuth dance in JavaScript. Tokens stay in the browser (memory/sessionStorage demo).',
    examTopics: ['SPA architecture', 'PKCE in browser', 'Public client', 'CORS considerations'],
  },
  {
    id: 'api-access',
    name: 'API Access',
    path: '/labs/api-access',
    pingoneType: 'Worker / Service + Resource Server',
    grant: 'Bearer token validation',
    clientType: 'Resource server',
    description: 'Protected API endpoints that validate PingOne-issued JWT access tokens (signature, issuer, audience, expiry).',
    examTopics: ['Resource server', 'JWT validation', 'Scopes', 'Audience (aud) claim'],
  },
  {
    id: 'long-session',
    name: 'Long-Running Sessions',
    path: '/labs/long-session',
    pingoneType: 'Web App (OIDC)',
    grant: 'Authorization Code + Refresh Token',
    clientType: 'Confidential',
    description: 'Demonstrates refresh token rotation to maintain sessions beyond access token lifetime without re-authentication.',
    examTopics: ['Refresh tokens', 'offline_access scope', 'Token rotation', 'Session lifetime policies'],
  },
  {
    id: 'm2m',
    name: 'Machine-to-Machine',
    path: '/labs/m2m',
    pingoneType: 'Worker App',
    grant: 'Client Credentials',
    clientType: 'Confidential',
    description: 'Service-to-service authentication with no user context. Requests an access token directly from the token endpoint.',
    examTopics: ['Client Credentials grant', 'Worker app', 'No refresh token', 'Service scopes'],
  },
  {
    id: 'device-flow',
    name: 'Device Authorization',
    path: '/labs/device-flow',
    pingoneType: 'Device Authorization',
    grant: 'Device Authorization (RFC 8628)',
    clientType: 'Public',
    description: 'Simulates a smart TV or other input-constrained device. The TV displays a user code while you authorize on a phone or laptop; the device polls for tokens.',
    examTopics: ['Device Authorization Grant', 'user_code / device_code', 'Polling interval', 'Slow_down handling', 'No redirect URI on device'],
  },
  {
    id: 'ciba',
    name: 'CIBA Support',
    path: '/labs/ciba',
    pingoneType: 'Web App with CIBA',
    grant: 'Client Initiated Backchannel Authentication',
    clientType: 'Confidential',
    description: 'Decoupled authentication: the client initiates auth via backchannel while the user approves on their authentication device. Requires a DaVinci CIBA flow policy.',
    examTopics: ['CIBA flow', 'login_hint', 'auth_req_id polling', 'binding_message', 'DaVinci CIBA flow (acr_values)'],
  },
  {
    id: 'token-exchange',
    name: 'Token Exchange',
    path: '/labs/token-exchange',
    pingoneType: 'Worker App',
    grant: 'Token Exchange (RFC 8693)',
    clientType: 'Confidential',
    description: 'Exchange one token for another (e.g., swap a user token for a downstream API token with reduced scope).',
    examTopics: ['RFC 8693', 'subject_token', 'actor_token', 'Delegation patterns'],
  },
  {
    id: 'enhanced-security',
    name: 'Enhanced Security Controls',
    path: '/labs/enhanced-security',
    pingoneType: 'Web App (OIDC)',
    grant: 'Authorization Code + PKCE + PAR',
    clientType: 'Confidential',
    description: 'Demonstrates Pushed Authorization Requests (PAR), mandatory PKCE, and optional step-up authentication via acr_values.',
    examTopics: ['PAR', 'PKCE enforcement', 'Step-up auth (acr_values)', 'OAuth security best practices'],
  },
];

export function getLab(id) {
  return labs.find((lab) => lab.id === id);
}
